SELECT CAST(S.LAT_N AS DECIMAL(10, 4) ) AS MEDIAN FROM STATION AS S 
WHERE 
    (SELECT count(Lat_N) FROM STATION WHERE Lat_N < S.LAT_N ) = 
    (SELECT count(Lat_N) FROM STATION WHERE Lat_N > S.LAT_N )